<?
namespace tei187\Resources\ISO4217;

const Specifics = [
    'aed' => [ ],
    'afn' => [ ],
    'all' => [ ],
    'amd' => [ ],
    'ang' => [ ],
    'aoa' => [ ],
    'ars' => [ ],
    'aud' => [ ],
    'awg' => [ ],
    'azm' => [ ],
    'bam' => [ ],
    'bbd' => [ ],
    'bdt' => [ ],
    'bgn' => [ ],
    'bhd' => [ 'minor' => [ 'd' => 3 ] ],
    'bif' => [ 'minor' => [ 'u' => false ] ],
    'bmd' => [ ],
    'bnd' => [ ],
    'bob' => [ ],
    'brl' => [ ],
    'bsd' => [ ],
    'btn' => [ ],
    'bwp' => [ ],
    'byn' => [ ],
    'bzd' => [ ],
    'cad' => [ ],
    'cdf' => [ ],
    'chf' => [ ],
    'clp' => [ 'minor' => [ 'u' => false ] ],
    'cny' => [ ],
    'cop' => [ ],
    'crc' => [ ],
    'cuc' => [ ],
    'cup' => [ ],
    'cve' => [ ],
    'czk' => [ ],
    'djf' => [ 'minor' => [ 'u' => false ] ],
    'dkk' => [ ],
    'dzd' => [ ],
    'dop' => [ ],
    'egp' => [ ],
    'eur' => [ ],
    'ern' => [ ],
    'etb' => [ ],
    'fjd' => [ ],
    'fkp' => [ ],
    'gbp' => [ ],
    'gel' => [ ],
    'ghs' => [ ],
    'gip' => [ ],
    'gmd' => [ ],
    'gnf' => [ 'minor' => [ 'u' => false ] ],
    'gtq' => [ ],
    'gyd' => [ ],
    'hnl' => [ ],
    'hkd' => [ ],
    'hrk' => [ ],
    'htg' => [ ],
    'huf' => [ ],
    'idr' => [ ],
    'ils' => [ ],
    'inr' => [ ],
    'iqd' => [ 'minor' => [ 'd' => 3 ] ],
    'irr' => [ ],
    'isk' => [ 'minor' => [ 'u' => false ] ],
    'jmd' => [ ],
    'jod' => [ 'minor' => [ 'd' => 3 ] ],
    'jpy' => [ 'minor' => [ 'u' => false ] ],
    'kes' => [ ],
    'kgs' => [ ],
    'khr' => [ ],
    'kmf' => [ 'minor' => [ 'u' => false ] ],
    'kpw' => [ ],
    'krw' => [ 'minor' => [ 'u' => false ] ],
    'kwd' => [ 'minor' => [ 'd' => 3 ] ],
    'kyd' => [ ],
    'kzt' => [ ],
    'lak' => [ ],
    'lbp' => [ ],
    'lkr' => [ ],
    'lrd' => [ ],
    'lsl' => [ ],
    'lyd' => [ 'minor' => [ 'd' => 3 ] ],
    'mad' => [ ],
    'mdl' => [ ],
    'mga' => [ ],
    'mkd' => [ 'minor' => [ 'u' => false ] ],
    'mmk' => [ ],
    'mnt' => [ ],
    'mop' => [ ],
    'mru' => [ ],
    'mur' => [ ],
    'mvr' => [ ],
    'mxn' => [ ],
    'myr' => [ ],
    'mwk' => [ ],
    'mzn' => [ ],
    'nad' => [ ],
    'nio' => [ ],
    'ngn' => [ ],
    'npr' => [ ],
    'nok' => [ ],
    'nzd' => [ ],
    'omr' => [ 'minor' => [ 'd' => 3 ] ],
    'pab' => [ ],
    'pen' => [ ],
    'pgk' => [ ],
    'php' => [ ],
    'pkr' => [ ],
    'pln' => [ ],
    'pyg' => [ 'minor' => [ 'u' => false ] ],
    'qar' => [ ],
    'ron' => [ ],
    'rsd' => [ ],
    'rub' => [ ],
    'rwf' => [ 'minor' => [ 'u' => false ] ],
    'sar' => [ ],
    'sbd' => [ ],
    'scr' => [ ],
    'sdg' => [ ],
    'sek' => [ ],
    'sgd' => [ ],
    'shp' => [ ],
    'sll' => [ ],
    'sos' => [ ],
    'srd' => [ ],
    'ssp' => [ ],
    'stn' => [ ],
    'svc' => [ ],
    'syp' => [ ],
    'szl' => [ ],
    'thb' => [ ],
    'tjs' => [ ],
    'tmt' => [ ],
    'tnd' => [ 'minor' => [ 'd' => 3, ] ],
    'top' => [ ],
    'try' => [ ],
    'ttd' => [ ],
    'twd' => [ ],
    'tzs' => [ ],
    'uah' => [ ],
    'ugx' => [ 'minor' => [ 'u' => false ] ],
    'usd' => [ ],
    'uyu' => [ ],
    'uzs' => [ ],
    'ves' => [ ],
    'vnd' => [ 'minor' => [ 'u' => false ] ],
    'vuv' => [ 'minor' => [ 'u' => false ] ],
    'wst' => [ ],
    'xaf' => [ 'minor' => [ 'u' => false ] ],
    'xcd' => [ ],
    'xof' => [ 'minor' => [ 'u' => false ] ],
    'xpf' => [ 'minor' => [ 'u' => false ] ],
    'yer' => [ ],
    'zar' => [ ],
    'zmw' => [ ],
    'zwl' => [ ],
];